# Script to deploy on the render cloud platform

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: bounceapp/render-action@0.6.0
      with:
        render-token: ${{secrets.RENDER_API_KEY}}
        github-token: ${{secrets.ACC_API_KEY}}
        service-id: "srv-cg9d9nu4dad5p6q8nu3g"

        retries: 20
        wait: 16000
        sleep: 30000

